### ISSUE TITLE
Multiple digital inputs/interrupts per port

### ISSUE THREAD

**Issue by lyzadanger** [rwaldron/tessel-io#10]
Hello!

I'm having trouble getting a Tessel 2 to work with more than one `Button` (i.e. interrupt-utilizing digital input) on each port (A, B). I believe this may also extend to the use of more than one digital input of any sort per port. I can have one button per port, but trying to have multiple buttons per port—using any combination of interrupt-supporting pins—does not work.

More details:

```
var btn1 = new five.Button('a2');
var btn1 = new five.Button('a5');

btn1.on('press', () => {
  console.log('this will never fire');
});
btn2.on('press', () => {
  console.log('this will fire when you press the attached button, as expected');
});
```

Whichever is the last defined component on the port wins (i.e. last object created).

This works (only one interrupt-digital-in per port):

```
var btn1 = new five.Button('a2');
var btn2 = new five.Button('b5');

// ...
```

This does not work as expected:

```
  var btn1 = new five.Pin({
    pin: 'a5',
    type: 'digital',
    mode: 0
  });
  var btn2 = new five.Pin({
    pin: 'a6',
    type: 'digital',
    mode: 0
  });
```

`btn1.value` is always `0` and various events will not fire. `btn2` behaves as you'd expect a digital input to behave. This particular symptom makes me think this one-per-port limitation would extend to any digital input, not just buttons.

Perhaps something in [this commit](https://github.com/rwaldron/tessel-io/commit/33f2b690b2aff8a6408764237e4c457310fa779d) could have introduced something unintentional? Or, is there a real/hard limitation here?

I'm trying to build something that has four buttons, so... yeah :D.

(this is `tessel-io` at latest, `0.6.2`).

**Comment by rwaldron** [comment]
Amazing catch on this one. The commit you cited was the issue and I should've been more thorough with testing. I've reverted to 0.6.1 and made a new release at 0.6.4
