### ISSUE TITLE
Possibly Incorrect ADC Resolution

### ISSUE THREAD

**Issue by wagenet** [rwaldron/tessel-io#22]
I'm walking through the J5IK guides and on the [pentiometer one](https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit/experiment-3-reading-a-potentiometer), I found that `scaleTo` is too small by a factor of 4. Poking around with logging, I discovered that this is because the raw value is 0-1023, but the sensor resolution is listed as 4096. This means that when we scale, we're only a quarter of what we should be. The resolution comes from the board's RESOLUTION.ADC which is 4096 in this code. Is that an error? or is the bug elsewhere?

**Comment by wagenet** [comment]
To confirm, things work as expected when I change RESOLUTION.ADC:

```js
class FixedTessel extends Tessel {
  get RESOLUTION() {
    return {
      ADC: 1024
    };
  }
}
```

**Comment by rwaldron** [comment]
Excellent bug!

**Comment by rwaldron** [comment]
`tessel-io@1.1.0`
